version: '3.1'
services:

  mysql:
    image: mysql:latest
    container_name: planet4_mysql
    ports:
      - 3306:3306
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.2

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:4.7
    container_name: myadmin
    depends_on:
      - mysql
    expose:
      - "80"
    ports:
      - "8083:80"
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.5

  planet4:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: greenpeace/planet4
    container_name: planet4
    restart: always
    ports:
      - 9000
    depends_on:
      - mysql
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.3

  nginx:
    image: diegol/nginx:alpine
    container_name: planet4_nginx
    depends_on:
      - mysql
      - planet4
    ports:
      - 80:80
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.4


networks:
  planet4_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
