version: '3.1'
services:

  mysql:
    image: mysql:latest
    container_name: planet4_mysql
    ports:
      - 3306:3306
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.2

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:4.7
    container_name: myadmin
    depends_on:
      - mysql
    expose:
      - "80"
    ports:
      - "8083:80"
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.5

  planet4:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: greenpeace/planet4
    container_name: planet4
    restart: always
    ports:
      - 9000
    depends_on:
      - mysql
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.3

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: greenpeace/planet4_nginx
    container_name: planet4_nginx
    depends_on:
      - mysql
      - planet4
    ports:
      - 80:80
      - 443:443
    env_file:
      - variables.env
    networks:
      planet4_network:
        ipv4_address: 172.20.0.4

  redis:
    image: redis:4-alpine
    networks:
      planet4_network:
        ipv4_address: 172.20.0.6
    volumes:
      - ./persistence/redis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8084:8081
    networks:
      planet4_network:
        ipv4_address: 172.20.0.7

networks:
  planet4_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
